### PR TITLE
core: frontend: VideoStreamCreationDialog: Add default name for stream

### PR DESCRIPTION
**Pull request by patrickelectric**
image

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
Oh, since you are messing with this dialog, the endpoint helper only works when we press the "+" button.

**Comment by patrickelectric** [comment]
> Oh, since you are messing with this dialog, the endpoint helper only works when we press the "+" button.

What ? Can you open an issue ? We can address that in another PR

**Review by ES-Alexander — CHANGES_REQUESTED** [review]
I feel like including `/dev/video0` makes it seem potentially not arbitrary. If it's possible to have a placeholder of "My Video Stream" or something that seems like it would be clearer.

**Comment by patrickelectric** [comment]
> I feel like including `/dev/video0` makes it seem potentially not arbitrary. If it's possible to have a placeholder of "My Video Stream" or something that seems like it would be clearer.

That will generate conflicts since the name can't be equal between streams, having the device name is safer.
We also don't have access to the number of video streams already used on the edit component to increase a index or something closer to it.
We can use 'Stream X', but that's also not helpful as name compared to device name.

**Comment by ES-Alexander** [comment]
Ok, fair enough.
In that case can we change the field name to "Stream nickname"? :-)

**Comment by patrickelectric** [comment]
> Ok, fair enough. In that case can we change the field name to "Stream nickname"? :-)

Is there a reason to use "nickname" over "name" ? it can add unnecessary internal changes on code and when integrating others systems, since name is what we use internally and in the API.

**Comment by ES-Alexander** [comment]
> Is there a reason to use "nickname" over "name" ?

"Nickname" comes across as "this is what _you_ want to call it - only for human display/convenience". "Name" _could_ be something that the computer cares about, and having the device source included in the default name makes that seem more possible/likely (because that information isn't shown elsewhere in the configuration).

It's definitely possible to reason your way to the fact that if you're clicking on the "add stream" option for a given camera then the computer must already know the information it needs to about where that camera is and how it can connect to it, but a user shouldn't need to do that reasoning - it should just be unambiguous to start with :-)

**Comment by patrickelectric** [comment]
> > Is there a reason to use "nickname" over "name" ?
> 
> "Nickname" comes across as "this is what _you_ want to call it - only for human display/convenience". "Name" _could_ be something that the computer cares about, and having the device source included in the default name makes that seem more possible/likely (because that information isn't shown elsewhere in the configuration).
> 
> It's definitely possible to reason your way to the fact that if you're clicking on the "add stream" option for a given camera then the computer must already know the information it needs to about where that camera is and how it can connect to it, but a user shouldn't need to do that reasoning - it should just be unambiguous to start with :-)

"Name" is how camera manager, camera manager rest api, QGC and the mavlnk protocol spec name the field used for the human name of the stream. But if you think that "nickname" is better, I just changed it.

**Pull request merged**
