### PR TITLE
core: tools: mavlink2rest: Update mavlink2rest to 0.11.10

### PR DESCRIPTION
**Pull request by patrickelectric**
New:
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.8
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.9
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.10

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by Williangalvani** [comment]
is the image built by CI? I can only find a `update_mavlink2rest_again2`

**Comment by patrickelectric** [comment]
> is the image built by CI? I can only find a `update_mavlink2rest_again2`

They are the same thing, I forgot to create a second PR with changes on the CI, that's what `again2` has.

**Comment by patrickelectric** [comment]
@rafaellehmkuhl @Williangalvani can we merge this ?

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl @Williangalvani can we merge this ?

I didn't test extensively, but I'm using it without problems.

**Review by Williangalvani — APPROVED** [review]

**Comment by Williangalvani** [comment]
I did some testing and it seemed fine.

**Pull request merged**
