### PR TITLE
parameter editor: Move improvements

### PR DESCRIPTION
**Pull request by patrickelectric**
- Display in scientific units when necessary
- Add units in main viewer and in editor
- Select custom when value does not exist in options once editor is open
- Select force when value is outside range once editor is open
- Deselect custom when value is a know open
- Deselect force when value goes back to range
- Fix reset of force and custom when editor closes

https://user-images.githubusercontent.com/1215497/206581777-d032feb3-d5a7-4bde-9785-33d5b8863ccf.mp4

### CODE REVIEW

**Review by Williangalvani — CHANGES_REQUESTED** [review]
c8afaff8b2def829307c9265d0f6e8013aac50a9
 is doing more than it says in the commit message. Can you at least update the commit message to mention the force/custom thingies?

**Comment by patrickelectric** [comment]
@Williangalvani done.

**Comment by Williangalvani** [comment]
the force button is not showing up for me...
Screenshot 2022-12-09 at 11 19 16

**Comment by patrickelectric** [comment]
> the force button is not showing up for me... Screenshot 2022-12-09 at 11 19 16

I don't know how that was working on the first place, the editor is using `new_value` as a model and not `edited_param.value`, fixed that in the last commit.

**Comment by Williangalvani** [comment]
I can't type 0.01 for some reason. when I type ˜0.0˜ it replaces it with ˜0˜

**Comment by Williangalvani** [comment]
> I can't type 0.01 for some reason. when I type ˜0.0˜ it replaces it with ˜0˜

nevermind. localization issues. in pt-br it wants comma instead of period 🤦

**Review by Williangalvani — APPROVED** [review]

**Pull request merged**
