### PR TITLE
1.0.2 modifications

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by ES-Alexander** [comment]
As far as I can tell this doesn't notably change the interface (just bugfixes etc), but once it's merged we need to at least update the "latest stable version" download link (and date) in the `installation.md` file in the `BlueOS-1.0` and `BlueOS-1.1` branches of the docs repo.

**Comment by patrickelectric** [comment]
> As far as I can tell this doesn't notably change the interface (just bugfixes etc), but once it's merged we need to at least update the "latest stable version" download link (and date) in the `installation.md` file in the `BlueOS-1.0` and `BlueOS-1.1` branches of the docs repo.

this should be done only once the tag exists, the branch is not yet ready for it.

**Comment by patrickelectric** [comment]
ping @ES-Alexander

**Review by ES-Alexander — APPROVED** [review]
> > As far as I can tell this doesn't notably change the interface (just bugfixes etc), but once it's merged we need to at least update the "latest stable version" download link (and date) in the `installation.md` file in the `BlueOS-1.0` and `BlueOS-1.1` branches of the docs repo.
> 
> this should be done only once the tag exists, the branch is not yet ready for it.

Agreed - the docs update will need to happen after this gets merged (since it needs a release date specified), so feel free to merge and then we can update the docs accordingly :-)

**Pull request merged**
