### PR TITLE
Fix multiple streams issue with QGC and mavlink-router

### LINKED ISSUE #1011: bug: cameras inconsistently appearing in QGC
### Bug description

Brought up in [this forum post](https://discuss.bluerobotics.com/t/disable-automatic-video-display-on-qgroundcontrol/12109):

> QGroundControl with BlueOS will automatically display the video streams ... [but] the video changing function is not very reliable and having 3 cameras on our setup, most of the time only 1 or 2 show up and its inconsistent with which camera shows and which don’t.

### Steps to reproduce

1. Start multiple streams in BlueOS
2. Check QGC for available ones
3. Repeat with inconsistent results [NEEDS CONFIRMATION]

### Primary pain point(s)

Makes it harder to effectively use multiple cameras with BlueOS, and encourages using external applications for streaming any/all video instead of QGC (which fragments the user experience).

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #1011

### CODE REVIEW

**Review by joaoantoniocardoso — APPROVED** [review]
Great!

**Comment by patrickelectric** [comment]
Needs more test and investigation

**Comment by patrickelectric** [comment]
This still may break SITL since, from what I know, mavlink-router does not support multiple TCP servers, we should need to check if restarting the vehicle will not break the camera manager, since this is a TCP connection and we should handle disconnections.
@rafaellehmkuhl any tips ? @joaoantoniocardoso, please checkout

**Comment by rafaellehmkuhl** [comment]
> This still may break SITL since, from what I know, mavlink-router does not support multiple TCP servers, we should need to check if restarting the vehicle will not break the camera manager, since this is a TCP connection and we should handle disconnections. @rafaellehmkuhl any tips ? @joaoantoniocardoso, please checkout

From what I remember, it doesn't support multiple TCP servers indeed.

**Comment by patrickelectric** [comment]
> > This still may break SITL since, from what I know, mavlink-router does not support multiple TCP servers, we should need to check if restarting the vehicle will not break the camera manager, since this is a TCP connection and we should handle disconnections. @rafaellehmkuhl any tips ? @joaoantoniocardoso, please checkout
> 
> From what I remember, it doesn't support multiple TCP servers indeed.

So we may want to use 5760 in the end

**Comment by Williangalvani** [comment]
superseeded by #1122

**Pull request closed without merging**
