### PR TITLE
Fix bootloader date format

### LINKED ISSUE #1550: Bootloader version is not formatted correctly
Beta 17
image

### PR DESCRIPTION
**Pull request by patrickelectric**
image
Fix #1550

### CODE REVIEW

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]
It still looks very strange.
It starts with date, then theres time, then there's date again (year).

**Comment by patrickelectric** [comment]
> It still looks very strange. It starts with date, then theres time, then there's date again (year).

I'm not sure if I follow, can you be more explicit ?
This fix the current format that's broken, where it only shows until the first `:`

**Comment by rafaellehmkuhl** [comment]
> > It still looks very strange. It starts with date, then theres time, then there's date again (year).
> 
> I'm not sure if I follow, can you be more explicit ? This fix the current format that's broken, where it only shows until the first `:`

Previously, the output was incomplete, but it was just a date, so not confusing.

Right now the output is "day-of-the-week day month hour:minute timezone year (epoch)".

We should have something more straightforward like "day-of-the-week day month yeart timezone hour:minute (epoch)"

**Comment by patrickelectric** [comment]
@rafaellehmkuhl check the latest version

**Review by rafaellehmkuhl — APPROVED** [review]

**Pull request merged**
