### PR TITLE
core: bridges: Fix check for error message

### PR DESCRIPTION
**Pull request by patrickelectric**
I dream on a day where Python std will have type hints
I dream on a day without daily errors footprints
I dream on a day where Python will have a good documentation with types
I dream on a day with peace in my mind

Before:
image

After:
image

### CODE REVIEW

**Comment by patrickelectric** [comment]
Report from: https://discuss.bluerobotics.com/t/ekf3-lane-switch-1-warning-when-armed/12693/6?u=patrickelectric

**Comment by Williangalvani** [comment]
what is the output of bridges looking like right now?
I worry that this change could reintroduce the bug where things stop working because stdout gets full...
should we flush it once in a while?

**Comment by patrickelectric** [comment]
> what is the output of bridges looking like right now? I worry that this change could reintroduce the bug where things stop working because stdout gets full... should we flush it once in a while?

Check the commit body of: https://github.com/bluerobotics/BlueOS-docker/pull/1112/commits/182c9678ea5d2ab9036f8bdf86893f78a32ecd10

**Comment by Williangalvani** [comment]
Sounds good. still, we should make sure the time it takes now is range of "years", not "hours".

**Review by Williangalvani — APPROVED** [review]

**Comment by patrickelectric** [comment]
> Sounds good. still, we should make sure the time it takes now is range of "years", not "hours".

There is no more outputs in bridges if you don't use verbose mode

**Comment by Williangalvani** [comment]
> > Sounds good. still, we should make sure the time it takes now is range of "years", not "hours".
> 
> There is no more outputs in bridges if you don't use verbose mode

perfect =D

**Pull request merged**
