### PR TITLE
core: frontend: componenets: video-manager: Only show extra configuration under pirate mode

### PR DESCRIPTION
**Pull request by patrickelectric**
Extra configuration is a feature that is intended to be used by advanced users for now.

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
I don't get it. Why adding an RGB stream is non-pirate and adding a thermal camera is pirate?

**Comment by rafaellehmkuhl** [comment]
> > I don't get it. Why adding an RGB stream is non-pirate and adding a thermal camera is pirate?
> 
> Thermal is a hack way to have multiple streams in qgc, not a real thermal camera use

So it has nothing to do with thermal? Why do we call it that way?

**Comment by patrickelectric** [comment]
> > > I don't get it. Why adding an RGB stream is non-pirate and adding a thermal camera is pirate?
> > 
> > 
> > Thermal is a hack way to have multiple streams in qgc, not a real thermal camera use
> 
> So it has nothing to do with thermal? Why do we call it that way?

That's is the official name on the mavlink spec

**Review by Williangalvani — APPROVED** [review]

**Review by rafaellehmkuhl — APPROVED** [review]
Strange but fair 😅 
I will open an issue to remember getting this back once we bypass this workaround.

**Pull request merged**
