### PR TITLE
core: frontend: components: SystemCondition: Filter out docker binds in disks

### PR DESCRIPTION
**Pull request by patrickelectric**
There is no easy way to do it for now using sysinfo library and update linux2rest, hopefully more time or something better may be possible in the future.

### CODE REVIEW

**Comment by Williangalvani** [comment]
this seems to be doing something to the disks instead of ipv6...

**Comment by joaoantoniocardoso** [comment]
> this seems to be doing something to the disks instead of ipv6...

@patrickelectric you might have mistakenly kept the wrong part of the https://github.com/bluerobotics/BlueOS-docker/commit/45b58c5324fa7aa092ca2db6e3cbccf18dfbe9f9 commit..?

**Comment by patrickelectric** [comment]
@Williangalvani @joaoantoniocardoso I just fixed

**Review by joaoantoniocardoso — APPROVED** [review]
I didn't test it but LGTM

**Pull request merged**
