### PR TITLE
Add theme on top

### PR DESCRIPTION
**Pull request by patrickelectric**
https://user-images.githubusercontent.com/1215497/217019788-864f8352-b723-450d-b73d-e931f7a753bc.mp4

### CODE REVIEW

**Review by ES-Alexander — COMMENTED** [review]
I think the toggle is maybe the wrong way around, but it depends how you think about it.

In the docs when you're currently in dark mode it shows the sun, so you can click on it to get what you want. In this PR you've made it so that the icon shows what you're currently on, and you can click on that to change it to something else. Honestly not really sure what's better. I guess we can discuss in the meeting.

**Comment by patrickelectric** [comment]
@ES-Alexander just updated

**Comment by patrickelectric** [comment]
@ES-Alexander that is consistent with the pirate mode behavior

**Comment by patrickelectric** [comment]
@ES-Alexander I'm planning o create the next BlueOS release ASAP for the company meeting, so let me know what you think.

**Review by ES-Alexander — APPROVED** [review]
I'm fine either way, just good to have had the discussion. We should probably change the docs one to match, but that can be sorted out later :-)

**Pull request merged**
