### PR TITLE
Improve parameter editor based on SMS feedback

### PR DESCRIPTION
**Pull request by patrickelectric**
Includes: https://github.com/bluerobotics/BlueOS-docker/pull/1322

https://user-images.githubusercontent.com/1215497/212071603-f6fbf5f7-87fa-4689-89a5-84a0e312623e.mp4

### CODE REVIEW

**Review by Williangalvani — APPROVED** [review]
lgtm.

Any thoughts on making the "Reboot required" text red?

**Comment by patrickelectric** [comment]
> lgtm.
> 
> Any thoughts on making the "Reboot required" text red?

Red looks more as an error than a warning.

**Review by ES-Alexander — APPROVED** [review]
Looks great!

Could we also add tooltips to the Save and Load buttons for parameters files, just specifying "Save all parameters to a file" and "Load new parameters from a file"? :-)

I would prefer if the "Reboot Vehicle" button was in the header so that it follows you around other pages if you leave the parameters one, but not sure how hard that is to do.

**Comment by patrickelectric** [comment]
> Could we also add tooltips to the Save and Load buttons for parameters files, just specifying "Save all parameters to a file" and "Load new parameters from a file"? :-)

Isn't Save and Load clear enough on the parameter page ?

**Comment by ES-Alexander** [comment]
> Isn't Save and Load clear enough on the parameter page ?

At least for saving, it may not be clear whether they're saving all the current vehicle parameters, or just the ones currently shown in the table/display. Perhaps the tooltips should explicitly mention `.params` files, instead of just saying "a file".

**Comment by patrickelectric** [comment]
> > Isn't Save and Load clear enough on the parameter page ?
> 
> At least for saving, it may not be clear whether they're saving all the current vehicle parameters, or just the ones currently shown in the table/display. Perhaps the tooltips should explicitly mention `.params` files, instead of just saying "a file".

Done.

**Comment by patrickelectric** [comment]
We save it as "txt" since there is no rule for parameters files extensions, there a couple around.

**Pull request merged**
