### PR TITLE
bootstrap: bootstrap: Add missing timeout for requests.get

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Review by joaoantoniocardoso — APPROVED** [review]

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]
I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.

**Comment by patrickelectric** [comment]
> I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.

our code uses 0.2 is mostly all gets, I just moved this one to 0.5;

**Comment by patrickelectric** [comment]
> > I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.
> 
> our code uses 0.2 is mostly all gets, I just moved this one to 0.5;

Besides that, any timeout number suggestion ? Everything that I may put here will be more a shot than rocket science.

**Comment by patrickelectric** [comment]
To measure it, it takes 0.02 seconds on the system.

**Comment by joaoantoniocardoso** [comment]
> > > I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.
> > 
> > 
> > our code uses 0.2 is mostly all gets, I just moved this one to 0.5;
> 
> Besides that, any timeout number suggestion ? Everything that I may put here will be more a shot than rocket science.

For web things, I think 30s is more than enough, at least it is the default for firefox's requests.

**Comment by patrickelectric** [comment]
> > > > I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.
> > > 
> > > 
> > > our code uses 0.2 is mostly all gets, I just moved this one to 0.5;
> > 
> > 
> > Besides that, any timeout number suggestion ? Everything that I may put here will be more a shot than rocket science.
> 
> For web things, I think ~30s~ 300s is more than enough, at least it is the default for firefox's requests.
> 
> image

We are talking about a localhost json file with less than 100bytes, not a other side of the world full website.

**Comment by joaoantoniocardoso** [comment]
> > > > > I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.
> > > > 
> > > > 
> > > > our code uses 0.2 is mostly all gets, I just moved this one to 0.5;
> > > 
> > > 
> > > Besides that, any timeout number suggestion ? Everything that I may put here will be more a shot than rocket science.
> > 
> > 
> > For web things, I think ~30s~ 300s is more than enough, at least it is the default for firefox's requests.
> > image
> 
> We are talking about a localhost json file with less than 100bytes, not a other side of the world full website.

Okay, then I'd go with 1 or 1.5 seconds.

**Comment by rafaellehmkuhl** [comment]
> To measure it, it takes 0.02 seconds on the system.

When it's working perfectly.

**Comment by rafaellehmkuhl** [comment]
> > > I wouldn't put such a small timeout to be honest. If the service gets slight unresponsive, this will fail unnecessarily, since its a non-time-critical operation.
> > 
> > 
> > our code uses 0.2 is mostly all gets, I just moved this one to 0.5;
> 
> Besides that, any timeout number suggestion ? Everything that I may put here will be more a shot than rocket science.

A timeout shouldn't be defined by how much time the request usually takes, but by how much time we agree it starts being a problem (e.g.: user thinks his action didn't work).

This request happens every full moon, so I would put anything around 10 seconds without problems.

**Review by rafaellehmkuhl — APPROVED** [review]

**Pull request merged**
