### PR TITLE
core: frontend: wizard: move wifi connection to first step of wizard

### LINKED ISSUE #1781: wifi internet picking should be the first step
right now it is being done after picking the firmware version which doesn't work without internet

### PR DESCRIPTION
**Pull request by Williangalvani**
fix #1781

### CODE REVIEW

**Review by joaoantoniocardoso — COMMENTED** [review]
LGTM, someone needs to test it

**Review by joaoantoniocardoso — CHANGES_REQUESTED** [review]
UI is kinda broken: the fourth step is not on the top.

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/281e37e8-800d-4a9c-aeee-1a972c0fb504

Also, I think it should be something like:

```
# BlueOS Wizard
---
< Some introductory message like..: > Hello, this wizard will help you
 set up your vehicle for its first use! In order to fetch firmware and
 other data from the internet, please ensure that you have a wired
 internet connection, or click the button below to configure your WiFi connection.

[x] Trying to reach the internet via cable... Failed. 

[ask me later] [don't show again] [configure WiFi] [retry]
```

and then, the WiFi dialogue shows if you click there.

edit: We might then, remove the old 'welcome to BlueOS' message, would be redundant

**Comment by Williangalvani** [comment]
@joaoantoniocardoso wired internet is going to be very rare. I don't think it should be mentioned. The wifi step should already be skipped automatically if internet is detected in any form.

I do like the idea of a welcome text, and I'll trim the steps so we only have 4

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso wired internet is going to be very rare. I don't think it should be mentioned. The wifi step should already be skipped automatically if internet is detected in any form.
> 
> I do like the idea of a welcome text, and I'll trim the steps so we only have 4

I see... But do we want it to be rare? If we are designing Cockpit to handle multiple clients, I think the most common setup would be the vehicle connected to a router, and then I can imagine (at least half) of the users would prefer to just have the internet cable to that router too, sharing between all computers and vehicle.

**Comment by Williangalvani** [comment]
> I see... But do we want it to be rare? If we are designing Cockpit to handle multiple clients, I think the most common setup (for multiple clients) would be the vehicle connected to a router, and then I can imagine (at least half) of the users would prefer to just have the internet cable to that router too, sharing between all computers and vehicle.

I am confused, so all vehicles would be effectively wired together? :thinking:

**Review by joaoantoniocardoso — APPROVED** [review]

**Pull request merged**
