### PR TITLE
Allow user to enable raspberry camera legacy mode

### PR DESCRIPTION
**Pull request by patrickelectric**
image

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
Looks good, if it isn't too difficult, we might want to add a quick link to "restart now" in this dialogue:
image

**Comment by patrickelectric** [comment]
> Looks good, if it isn't too difficult, we might want to add a quick link to "restart now" in this dialogue: image

I don't know if that's possible, @rafaellehmkuhl ?

**Comment by rafaellehmkuhl** [comment]
> > Looks good, if it isn't too difficult, we might want to add a quick link to "restart now" in this dialogue: image
> 
> I don't know if that's possible, @rafaellehmkuhl ?

To add just the restart button, you would need to isolate it from the PowerMenu component, where it currently resides.
A faster option would be to just open the PowerMenu dialog, which is just a matter of importing the component and showing it.

**Comment by patrickelectric** [comment]
> > > Looks good, if it isn't too difficult, we might want to add a quick link to "restart now" in this dialogue: image
> > 
> > 
> > I don't know if that's possible, @rafaellehmkuhl ?
> 
> To add just the restart button, you would need to isolate it from the PowerMenu component, where it currently resides. A faster option would be to just open the PowerMenu dialog, which is just a matter of importing the component and showing it.

I think that we can let as it's for now and rework that later to make a generic "restart is required" component.

**Review by joaoantoniocardoso — APPROVED** [review]

**Pull request merged**
