### PR TITLE
Improve autopilot page

### PR DESCRIPTION
**Pull request by patrickelectric**
image

### CODE REVIEW

**Review by ES-Alexander — CHANGES_REQUESTED** [review]
IIRC it was also asked to improve the "Install Firmware" button icon. I couldn't think of a great one, but maybe something like `mdi-arrow-right-bold-outline`, or just removing the icon entirely?

**Comment by joaoantoniocardoso** [comment]
> 
maybe `mdi-download` but rotated 90° (`mdi-rotate-270`)? 
image

**Comment by patrickelectric** [comment]
> Also, the retrieve from cloud could be changed to mdi-cloud-download

Yes, I just did that.

What you guys think about ?
image
image
image

**Comment by patrickelectric** [comment]
> Also unsure whether we want to do the other autopilot page changes at the same time, or in a separate PR.

They are atomic changes, multiple PRs is preferred.

**Comment by joaoantoniocardoso** [comment]
> > Also, the retrieve from cloud could be changed to mdi-cloud-download
> 
> Yes, I just did that.
> 
> What you guys think about ?
> image image image

Great, for me the `tray-arrow-down` makes more sense for installation

**Comment by patrickelectric** [comment]
Lets wait for @ES-Alexander to see what he thinks, the latest version already contains it.

**Comment by joaoantoniocardoso** [comment]
@patrickelectric can you add a space here between the icon and the label?
image

**Comment by Williangalvani** [comment]
I don't like the "install firmware" icon. maybe a floppy disk, meaning "save"?  :thinking: 
image

**Comment by ES-Alexander** [comment]
I think I prefer @Williangalvani's save icon, or just no icon at all. `tray-arrow-down` doesn't really "feel" like installing to me.

**Comment by patrickelectric** [comment]
@ES-Alexander done.

**Review by ES-Alexander — APPROVED** [review]

**Pull request merged**
