### PR TITLE
core: move service logs to `/var/logs/blueos`

### LINKED ISSUE #839: bug: Service logs are not persistent between docker boots
### Bug description

When docker restart, service logs are lost, probably because `/root/.cache/` is not binded.

image

### Steps to reproduce

1.  Look at your service logs. There's always just one file. 

### Primary pain point(s)

If one power down BlueOS, the logs are lost.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### LINKED ISSUE #861: Logs should be moved to in /var/logs/blueos

### PR DESCRIPTION
**Pull request by rafaellehmkuhl**
Fix #839 
Fix #861

### CODE REVIEW

**Review by patrickelectric — APPROVED** [review]

**Comment by rafaellehmkuhl** [comment]
Important to notice: for the ones who already have an image running, a manual modification of the startup.json file is needed.

**Comment by patrickelectric** [comment]
> Important to notice: for the ones who already have an image running, a manual modification of the startup.json file is needed.

The beta 16 requires a new installation, so it should be no problem.

**Comment by rafaellehmkuhl** [comment]
> > Important to notice: for the ones who already have an image running, a manual modification of the startup.json file is needed.
> 
> The beta 16 requires a new installation, so it should be no problem.

Perfect

**Comment by rafaellehmkuhl** [comment]
@patrickelectric ready to go

**Pull request merged**
