### PR TITLE
frontend: video: Allow multiple IPs for each stream

### LINKED ISSUE #867: UI: Allow more than one IP on stream creation
`mavlink-camera-manager` supports it, but our frontend doesn't (validation kicks in).

Maybe a plus button besides the IP input box would be cool.

### PR DESCRIPTION
**Pull request by rafaellehmkuhl**
image

Fix #867

Image available at `rafaellehmkuhl/blueos-core`

### CODE REVIEW

**Review by Williangalvani — CHANGES_REQUESTED** [review]
Nice. Can you add a title/popover to the + button saying "Add new stream"?

Also, we need more validation. IIRC we only support multiple endpoints for UDP, and we need to ensure that the user doesn't try to mix rtsp and udp endpoints:

image

**Comment by rafaellehmkuhl** [comment]
> Nice. Can you add a title/popover to the + button saying "Add new stream"?
> 
> Also, we need more validation. IIRC we only support multiple endpoints for UDP, and we need to ensure that the user doesn't try to mix rtsp and udp endpoints:
> 
> image

Good catch. I wrongly assumed the behavior would be the same for RTSP and just tested UDP.

So to get it correctly:
- Can we have multiple IPs for UDP?
- Are we limited to one RTSP IP per stream?
- Can we have multiple multiple UDPs and one RTSP for the same stream?

@patrickelectric or @joaoantoniocardoso maybe can answer this better.

**Comment by patrickelectric** [comment]
> 

An UDP stream can have multiple UDP endpoint, a RTSP stream should have a single endpoint, you can't mix UDP and RTSP.

**Review by patrickelectric — CHANGES_REQUESTED** [review]
The style is a bit weird with the plus icon on the side of endpoint when there is multiple endpoints, a button bellow the Stream endpoint would be better.
image

We could also only enable the "Add" button if it's an UDP endpoint.

**Comment by rafaellehmkuhl** [comment]
> The style is a bit weird with the plus icon on the side of endpoint when there is multiple endpoints, a button bellow the Stream endpoint would be better. image
> 
> We could also only enable the "Add" button if it's an UDP endpoint.

image

Personally, I didn't like it. The plus sign is very intuitive and don't bloat the UI. @Williangalvani @joaoantoniocardoso what do you think?

**Comment by rafaellehmkuhl** [comment]
> > The style is a bit weird with the plus icon on the side of endpoint when there is multiple endpoints, a button bellow the Stream endpoint would be better. image
> > We could also only enable the "Add" button if it's an UDP endpoint.
> 
> image
> 
> Personally, I didn't like it. The plus sign is very intuitive and don't bloat the UI. @Williangalvani @joaoantoniocardoso what do you think?

From external voting, we keep the plus sign button.

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
