### PR TITLE
core: frontend: components: common: DefaultTooltip: Add Arrrgh prefix in pirate mode

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by Williangalvani** [comment]
I"m afraid this is a bit too much... we should ask for more opinions thought

**Review by ES-Alexander — COMMENTED** [review]
Lol, is there a screenshot of what this would look like? I'm not sure where this would appear.

**Comment by Williangalvani** [comment]
> Lol, is there a screenshot of what this would look like? I'm not sure where this would appear.

there you go:

https://user-images.githubusercontent.com/4013804/159807437-b3ceab4b-e1fc-4522-8062-686e4ad03c9b.mp4

**Comment by ES-Alexander** [comment]
Assuming these options are only available in pirate mode, I think a flag or crossbones symbol would be better :-)
The Arrrgh is amusing but is almost as much text as the thing it's annotating, so agreed with Willian that it's a bit much as is.

**Pull request closed without merging**
