### PR TITLE
core: nmea-injector: Cover it with tests

### LINKED ISSUE #557: core: nmea-injector: Create test with nmeasim

### PR DESCRIPTION
**Pull request by rafaellehmkuhl**
Uses [nmeasim](https://pypi.org/project/nmeasim/) to generate fake NMEA data.

~Unfortunatelly nmeasim does not have support for GNS messages, nor I could find much information about it. @Williangalvani @jaxxzer do you have any idea about this sentence type? If we have a sample message, I can add a hard-coded test to it.~ Added tests for GNS sentence type.

Fix #557

### CODE REVIEW

**Comment by patrickelectric** [comment]
@rafaellehmkuhl maybe this ?
https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_GNS.html

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl maybe this ? https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_GNS.html

Cool! Will try with those.
I was trying to access those trimble docs some time ago, but they were not loading. Probably my internet.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric added tests for GNS type. This required some additional changes, the came for good. 

The tests are now separated by mavlink's GPS_INPUT field, so the test structure doesn't change with new sentence types being added.

**Review by patrickelectric — CHANGES_REQUESTED** [review]
with the settings:
image

Master:
image

With: 
image


Results in:
image


I would also recommend tests to settings load.

**Comment by rafaellehmkuhl** [comment]
> with the settings: image
> 
> Master: image
> 
> With: image
> 
> Results in: image
> 
> I would also recommend tests to settings load.

Just to be sure: Is this happening if you change to any other image or just when using the 'add_more_tests'?

**Comment by rafaellehmkuhl** [comment]
@patrickelectric problem fixed and tests to settings added.

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
