### PR TITLE
core: frontend: Change pirate icon style to top bar

### PR DESCRIPTION
**Pull request by patrickelectric**
image

### CODE REVIEW

**Review by ES-Alexander — APPROVED** [review]
I like this, although it may also be worth in general making this the place to turn pirate mode on/off (e.g. instead of making the icon disappear when pirate mode is off, just make it grey/crossed out with a diagonal "cancel" line, and then you can click the icon to swap modes).

**Comment by patrickelectric** [comment]
> I like this, although it may also be worth in general making this the place to turn pirate mode on/off (e.g. instead of making the icon disappear when pirate mode is off, just make it grey/crossed out with a diagonal "cancel" line, and then you can click the icon to swap modes).

That's not easy if the icon does not exist. 
I would vote to merge at it's for now and work on the switch logic later.

**Comment by ES-Alexander** [comment]
> That's not easy if the icon does not exist.

Not really sure what you mean by this - I was suggesting we have an icon that is always displayed, but changes depending on whether or not pirate mode is on, and can be clicked to swap in and out of pirate mode.

Anyway, we can merge for now if that's not easy to do.

**Comment by patrickelectric** [comment]
> Not really sure what you mean by this - I was suggesting we have an icon that is always displayed, but changes depending on whether or not pirate mode is on, and can be clicked to swap in and out of pirate mode.

My point is how exactly do it, we are going to change the icon ? We are going to change the color ? What is the desired behavior of the UI

**Comment by ES-Alexander** [comment]
I think changing icons is likely the most intuitive. Maybe swap between `pirate` (or `skull-crossbones`) and `emoticon-happy-outline` (or `emoticon-cool-outline`), with a tooltip that says "Click to {en/dis}able pirate mode."

**Comment by joaoantoniocardoso** [comment]
@patrickelectric The hover/click actions are actually triggering the health icon

**Pull request merged**
