### PR TITLE
Add usb otg ethernet

### LINKED ISSUE #1020: feature: Enable usb-otg for Pi4
Useful to use the same cable as for network interface and power the Pi
E.g: https://forums.raspberrypi.com/viewtopic.php?t=243966

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #1020 

image

It works like a charm once the DHCP server is enabled
image

To use with mac and having internet access at the same time:

image

image

image

### CODE REVIEW

**Comment by patrickelectric** [comment]
My point with the docs is that the feature is not complete, future PRs will change the documentation and it worth more to do it before our next beta release.

**Comment by joaoantoniocardoso** [comment]
I just realized that I don't have the cable to properly test/use it, but I was expecting to at least see the USB option in the menu...

Might be relevant:

image

image

**Comment by patrickelectric** [comment]
@joaoantoniocardoso did you reboot your raspberry ?

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso did you reboot your raspberry ?

Cool, now I see it hahaha

image

image

**Review by joaoantoniocardoso — APPROVED** [review]
Didn't test 'cause my cable doesn't have data. Looks good

**Comment by patrickelectric** [comment]
Doc: https://github.com/bluerobotics/ardusub-zola/pull/73

**Comment by ES-Alexander** [comment]
`docs-needed` gets changed to `docs-complete` once a relevant documentation PR has been approved. PRs that need docs should have a docs label to indicate the state.

**Pull request merged**
