### PR TITLE
core: frontend: Change icon and tooltip for SDP URL copy button

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
image

### CODE REVIEW

**Review by patrickelectric — APPROVED** [review]

**Comment by Williangalvani** [comment]
I feel like content-copy makes more sense. I'm pretty sure I've seen it used for link plenty of times
https://pictogrammers.com/library/mdi/icon/content-copy/

**Comment by joaoantoniocardoso** [comment]
> I feel like content-copy makes more sense. I'm pretty sure I've seen it used for link plenty of times https://pictogrammers.com/library/mdi/icon/content-copy/

Icon names are not always the best guess for their use, but would the [`content-copy`](https://pictogrammers.com/library/mdi/icon/content-copy/) be better suited than [`file-link`](https://pictogrammers.com/library/mdi/icon/file-link/) in this case?

**Comment by patrickelectric** [comment]
@joaoantoniocardoso @Williangalvani what is the status of this PR ?

**Comment by joaoantoniocardoso** [comment]
@patrickelectric I was waiting for @Williangalvani to show examples or further reasoning against the icon change.

**Review by ES-Alexander — APPROVED** [review]
LGTM :-)

Willian, if we were _showing_ the file url here then I'd agree that `content-copy` would make more sense (since there would be clear content being copied), but since it just says "File URL" with a download button then I think the `file-link` makes more sense in this case.

**Review by Williangalvani — APPROVED** [review]
yeah, I dont have THAT strong feelings about this

**Pull request merged**
