### PR TITLE
core: frontend: lock in to detected port for extensions

### PR DESCRIPTION
**Pull request by Williangalvani**
~needs testing~ it seems fine on my end, but more testing is welcome

williangalvani/blueos-core:lock_port

### CODE REVIEW

**Review by joaoantoniocardoso — CHANGES_REQUESTED** [review]
The extensions are not working unless when they're in full screen

**Comment by joaoantoniocardoso** [comment]
@Williangalvani got the same behavior w/ the updated patch:

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/b6e86a2b-1f3f-4fe5-88f8-9bd2a1cad00e

**Comment by Williangalvani** [comment]
> @Williangalvani, I got the same behavior w/ the updated patch:
> 
>  almost_always_doest_load_unless_on_full_screen_mode.mp4

can you check what happens if you do right-click -> reload iframe?

**Comment by joaoantoniocardoso** [comment]
> > @Williangalvani, I got the same behavior w/ the updated patch:
> > almost_always_doest_load_unless_on_full_screen_mode.mp4
> 
> can you check what happens if you do right-click -> reload iframe?


https://github.com/bluerobotics/BlueOS-docker/assets/5920286/7e9971cb-4791-4bd4-83d5-ec1473c17d21

**Review by joaoantoniocardoso — APPROVED** [review]
Cool, it's working fine now

**Comment by ES-Alexander** [comment]
Relevant docs should go in `development/extensions`, and possibly in `advanced-usage#extensions-manager`

**Review by patrickelectric — APPROVED** [review]

**Comment by ES-Alexander** [comment]
I accidentally mixed this up with #1843.

**Pull request merged**
